export const GET_CARS_LOADING = 'GET_CARS_LOADING';
export const GET_CARS_SUCCESS = 'GET_CARS_SUCCESS';
export const GET_CARS_ERROR = 'GET_CARS_ERROR';

export const GET_CAR_BY_ID_LOADING = "GET_CAR_BY_ID_LOADING";
export const GET_CAR_BY_ID_SUCCESS = "GET_CAR_BY_ID_SUCCESS";
export const GET_CAR_BY_ID_ERROR = "GET_CAR_BY_ID_ERROR";

export const DELETE_CAR_LOADING = "DELETE_CAR_LOADING";
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const DELETE_CAR_ERROR = "DELETE_CAR_ERROR";

export const ADD_CAR_LOADING = "ADD_CAR_LOADING";
export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS";
export const ADD_CAR_ERROR = "ADD_CAR_ERROR";

export const EDIT_CAR_LOADING = "EDIT_CAR_LOADING";
export const EDIT_CAR_SUCCESS = "EDIT_CAR_SUCCESS";
export const EDIT_CAR_ERROR = "EDIT_CAR_ERROR";


export const CLEAR_SUCCESS_CAR = "CLEAR_SUCCESS_CAR";
export const CLEAR_ERRORS_CAR = "CLEAR_ERRORS_CAR";
